export const API_ENDPOINTS = {
  AI_WORKSPACE: "/api/ai/workspace",
  AI_ANSWER: "/api/ai/answer",
  CMS_UPLOAD: "/api/cms/upload",
  CMS_QUEUE: "/api/cms/queue",
  CMS_OCR: "/api/cms/ocr",
  CMS_LAYOUT: "/api/cms/layout",
  CMS_DIAGRAMS: "/api/cms/diagrams",
  CMS_STRUCTURING: "/api/cms/structuring",
  CMS_SCHEMA: "/api/cms/schema",
  CMS_VALIDATION: "/api/cms/validation",
  CMS_WRITE: "/api/cms/write",
  CMS_REVIEW: "/api/cms/review",
  CMS_SAVE: "/api/cms/save",
  CMS_GIT: "/api/cms/git",
  CMS_HISTORY: "/api/cms/history",
  CMS_RECOVERY: "/api/cms/recovery",
  CMS_BULK: "/api/cms/bulk",
  CMS_REBUILD: "/api/cms/rebuild",
  CMS_PIPELINE_DEBUG: "/api/cms/debug/pipeline",
  CMS_METADATA: "/api/cms/metadata",
};
